domain = "WestAfrica"
subdomain = "Regional"
model_resolution = "1km"
systemModel = "crest"
nowcast_model_name = "linda" # options are ['naive', 'lagrangian', 'steps', 'linda', 'convlstm']
systemName = systemModel.upper() + " " + domain.upper() + " " + subdomain.upper()
ef5Path = "/Shared/lss_hvergaraarrieta/tools/EF5/bin/ef5" 
statesPath = "states/"
precipFolder = "precip/"
precipEF5Folder = "precipEF5/"
modelStates = ["crest_SM", "kwr_IR", "kwr_pCQ", "kwr_pOQ"]
templatePath = "templates/"
templates = "ef5_control_template.txt"
DATA_ASSIMILATION = False
assimilationPath = ""
assimilationLogs = []
dataPath = "outputs/"
qpf_store_path = 'qpf_store/'
tmpOutput = dataPath + "tmp_output_" + systemModel + "/"
SEND_ALERTS = False
smtp_server = "smtp.gmail.com"
smtp_port = 587
account_address = "model_alerts@gmail.com"
account_password = "supersecurepassword9000"
alert_sender = "Real Time Model Alert" # can also be the same as account_address
alert_recipients = ["fixer1@company.com", "fixer2@company.com", "panic@company.com",...]
copyToWeb = False
HindCastMode = False
HindCastDate = "2020-01-10 10:00" #"%Y-%m-%d %H:%M" UTC
# Email associated to GPM account
email = 'vrobledodelgado@uiowa.edu'
server = 'https://jsimpsonhttps.pps.eosdis.nasa.gov/imerg/gis/early/'
